"use client";

import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Share2, Image as ImageIcon, PaintBucket, Loader2 } from "lucide-react";
import Image from "next/image";
import * as htmlToImage from "html-to-image";

export default function InspirationPage() {
  const [quote, setQuote] = useState("Peace comes from within. Do not seek it without.");
  const [author, setAuthor] = useState("Siddhartha Gautama");
  const [isLoading, setIsLoading] = useState(false);
  const [bgMode, setBgMode] = useState<"gradient" | "realistic">("gradient");
  const [bgSeed, setBgSeed] = useState(1);
  const cardRef = useRef<HTMLDivElement>(null);

  const fetchNewQuote = async () => {
    setIsLoading(true);
    try {
      setBgSeed(Date.now()); // change realistic background instantly
      const res = await fetch("/api/quote", { method: "POST" });
      if (!res.ok) throw new Error("Failed to fetch quote");
      const data = await res.json();
      setQuote(data.quote);
      setAuthor(data.author);
    } catch (err) {
      console.error(err);
      alert("Failed to generate quote. Try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleShare = async () => {
    if (!cardRef.current) return;
    try {
      // 1. Convert to Image
      const dataUrl = await htmlToImage.toPng(cardRef.current, {
        quality: 1.0,
        pixelRatio: 2, // High resolution for IG
      });

      // 2. Auto-Download for the user
      const link = document.createElement("a");
      link.download = `welgpt-quote-${Date.now()}.png`;
      link.href = dataUrl;
      link.click();

      // 3. Native Share (if supported on mobile)
      if (navigator.share) {
        const blob = await (await fetch(dataUrl)).blob();
        const file = new File([blob], "quote.png", { type: "image/png" });
        await navigator.share({
          title: "WelGPT Inspiration",
          text: `"${quote}" - ${author}\n\nGenerated by WelGPT AI Coach.`,
          url: "https://app.welgpt.space",
          files: [file],
        });
      }
    } catch (error) {
      console.error("Error generating image", error);
      alert("Image saved! (Native share sheet is only supported on mobile devices)");
    }
  };

  return (
    <div className="max-w-4xl mx-auto relative z-10 pt-4 pb-20 h-full flex flex-col items-center justify-center">
      <header className="mb-8 text-center">
        <motion.div 
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            className="inline-flex items-center justify-center p-4 rounded-full mb-4"
        >
          <Image src="/logo-icon.png" alt="WelGPT" width={40} height={40} className="object-contain" priority />
        </motion.div>
        <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-3xl md:text-5xl font-bold mb-3 tracking-tight text-white"
        >
          Daily <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-violet-400">Inspiration.</span>
        </motion.h1>
      </header>

      {/* Mode Toggles */}
      <motion.div 
        initial={{ opacity: 0 }} 
        animate={{ opacity: 1 }} 
        className="flex items-center bg-[#111127] rounded-full p-1 border border-white/10 mb-8"
      >
        <button 
          onClick={() => setBgMode("gradient")}
          className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium transition-all ${bgMode === "gradient" ? "bg-white/10 text-white" : "text-gray-400 hover:text-gray-200"}`}
        >
          <PaintBucket size={16} /> Gradient
        </button>
        <button 
          onClick={() => setBgMode("realistic")}
          className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium transition-all ${bgMode === "realistic" ? "bg-white/10 text-white" : "text-gray-400 hover:text-gray-200"}`}
        >
          <ImageIcon size={16} /> Realistic AI
        </button>
      </motion.div>

      {/* The Downloadable Quote Card */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="w-full max-w-lg relative"
      >
        <div 
          ref={cardRef} 
          className="relative rounded-3xl overflow-hidden aspect-square flex flex-col items-center justify-center p-12 text-center border border-white/20 shadow-2xl"
          style={{ backgroundColor: bgMode === "gradient" ? "#0f0f23" : "#000" }}
        >
          {/* Background Layer */}
          <AnimatePresence mode="wait">
            {bgMode === "gradient" ? (
              <motion.div 
                key="gradient"
                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                className="absolute inset-0 bg-gradient-to-br from-violet-600/40 via-[#0f0f23] to-teal-600/40"
              />
            ) : (
              <motion.div 
                key={`img-${bgSeed}`}
                initial={{ opacity: 0 }} animate={{ opacity: 0.6 }} exit={{ opacity: 0 }} transition={{ duration: 1 }}
                className="absolute inset-0 bg-cover bg-center"
                style={{ backgroundImage: `url(https://picsum.photos/800/800?random=${bgSeed}&blur=2)` }}
              />
            )}
          </AnimatePresence>
          
          {/* Content Layer */}
          <div className="relative z-10 w-full">
            <Image src="/logo-icon.png" alt="WelGPT" width={32} height={32} className="mx-auto mb-8 opacity-80" />
            <h2 className="text-2xl md:text-3xl font-serif italic font-medium text-white leading-relaxed mb-6 drop-shadow-md">
              &quot;{quote}&quot;
            </h2>
            <p className="text-sm font-medium text-gray-300 tracking-widest uppercase drop-shadow-md">
              — {author}
            </p>
          </div>
          
          {/* Watermark for sharing */}
          <div className="absolute bottom-6 left-0 right-0 text-center z-10 opacity-50">
            <p className="text-[10px] font-mono tracking-widest text-white">APP.WELGPT.SPACE</p>
          </div>
        </div>
      </motion.div>

      {/* Action Buttons */}
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
        className="flex flex-wrap items-center justify-center gap-4 mt-10"
      >
        <button 
          onClick={fetchNewQuote}
          disabled={isLoading}
          className="flex items-center gap-2 px-6 py-3 rounded-full bg-white/10 hover:bg-white/20 text-white font-medium transition-colors border border-white/5 disabled:opacity-50"
        >
          {isLoading ? <Loader2 size={18} className="animate-spin" /> : <Sparkles size={18} />}
          {isLoading ? "Generating..." : "Generate New"}
        </button>
        <button 
          onClick={handleShare}
          className="flex items-center gap-2 px-6 py-3 rounded-full bg-gradient-to-r from-[#f09433] via-[#dc2743] to-[#bc1888] hover:opacity-90 text-white font-medium transition-opacity shadow-lg shadow-pink-500/20"
        >
          <Share2 size={18} />
          Share to IG
        </button>
      </motion.div>
    </div>
  );
}
