"use client";

import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Share2, Image as ImageIcon, PaintBucket, Loader2 } from "lucide-react";
import Image from "next/image";
import * as htmlToImage from "html-to-image";

const OFFLINE_QUOTES = [
  { quote: "The mind is everything. What you think you become.", author: "Siddhartha Gautama" },
  { quote: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { quote: "Neuroplasticity is the muscle of the soul.", author: "Dr. Andrew Huberman" },
  { quote: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
  { quote: "Focus is a matter of deciding what things you're not going to do.", author: "John Carmack" },
  { quote: "You have power over your mind - not outside events.", author: "Marcus Aurelius" }
];

export default function InspirationPage() {
  const [quote, setQuote] = useState("Peace comes from within. Do not seek it without.");
  const [author, setAuthor] = useState("Siddhartha Gautama");
  const [isLoading, setIsLoading] = useState(false);
  const [bgMode, setBgMode] = useState<"gradient" | "realistic" | "paper">("gradient");
  const [bgSeed, setBgSeed] = useState(1);
  const cardRef = useRef<HTMLDivElement>(null);

  const fetchNewQuote = async () => {
    setIsLoading(true);
    
    // Check if offline before attempting network request
    if (typeof navigator !== "undefined" && !navigator.onLine) {
      applyOfflineFallback();
      return;
    }

    try {
      setBgSeed(Date.now()); // change realistic background instantly
      const res = await fetch("/api/quote", { method: "POST" });
      if (!res.ok) throw new Error("Failed to fetch quote");
      const data = await res.json();
      setQuote(data.quote);
      setAuthor(data.author);
    } catch (err) {
      console.error("AI API failed or offline", err);
      applyOfflineFallback();
    } finally {
      setIsLoading(false);
    }
  };

  const applyOfflineFallback = () => {
    const randomQuote = OFFLINE_QUOTES[Math.floor(Math.random() * OFFLINE_QUOTES.length)];
    setQuote(randomQuote.quote);
    setAuthor(randomQuote.author);
    if (bgMode === "realistic") setBgMode("gradient"); // Force gradient mode if realistic since images need internet
    setIsLoading(false);
  };

  const handleShare = async () => {
    if (!cardRef.current) return;
    try {
      // 1. Convert to Image (iOS Safari Fixes)
      const dataUrl = await htmlToImage.toPng(cardRef.current, {
        quality: 1.0,
        pixelRatio: 2, // High resolution for IG
        useCORS: true, // MUST be true for Safari external images
        cacheBust: true, // Fixes Safari caching issues
        backgroundColor: bgMode === "paper" ? "#f5f5f5" : "#0f0f23", // Fallback background
      });

      // 2. Auto-Download for the user
      const link = document.createElement("a");
      link.download = `welgpt-quote-${Date.now()}.png`;
      link.href = dataUrl;
      link.click();

      // 3. Native Share (if supported on mobile)
      if (navigator.share) {
        const blob = await (await fetch(dataUrl)).blob();
        const file = new File([blob], "quote.png", { type: "image/png" });
        await navigator.share({
          title: "WelGPT Inspiration",
          text: `"${quote}" - ${author}\n\nGenerated by WelGPT AI Coach.`,
          url: "https://app.welgpt.space",
          files: [file],
        });
      }
    } catch (error) {
      console.error("Error generating image", error);
      alert("Image saved! (Native share sheet is only supported on mobile devices)");
    }
  };

  return (
    <div className="max-w-4xl mx-auto relative z-10 pt-4 pb-20 h-full flex flex-col items-center justify-center">
      <header className="mb-8 text-center">
        <motion.div 
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            className="inline-flex items-center justify-center p-4 rounded-full mb-4"
        >
          <Image src="/logo-icon.png" alt="WelGPT" width={40} height={40} className="object-contain" priority />
        </motion.div>
        <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-3xl md:text-5xl font-bold mb-3 tracking-tight text-white"
        >
          Daily <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-400 to-violet-400">Inspiration.</span>
        </motion.h1>
      </header>

      {/* Mode Toggles */}
      <motion.div 
        initial={{ opacity: 0 }} 
        animate={{ opacity: 1 }} 
        className="flex items-center bg-[#111127] rounded-full p-1 border border-white/10 mb-8 overflow-x-auto no-scrollbar max-w-full"
      >
        <button 
          onClick={() => setBgMode("gradient")}
          className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium transition-all whitespace-nowrap ${bgMode === "gradient" ? "bg-white/10 text-white" : "text-gray-400 hover:text-gray-200"}`}
        >
          <PaintBucket size={16} /> Gradient
        </button>
        <button 
          onClick={() => setBgMode("realistic")}
          className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium transition-all whitespace-nowrap ${bgMode === "realistic" ? "bg-white/10 text-white" : "text-gray-400 hover:text-gray-200"}`}
        >
          <ImageIcon size={16} /> Realistic AI
        </button>
        <button 
          onClick={() => setBgMode("paper")}
          className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium transition-all whitespace-nowrap ${bgMode === "paper" ? "bg-white/10 text-white" : "text-gray-400 hover:text-gray-200"}`}
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/></svg> 
          Vintage Paper
        </button>
      </motion.div>

      {/* The Downloadable Quote Card */}
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
        className="w-full max-w-lg relative"
      >
        <div 
          ref={cardRef} 
          className="relative rounded-3xl overflow-hidden aspect-square flex flex-col items-center justify-center p-12 text-center border border-white/20 shadow-2xl"
          style={{ backgroundColor: bgMode === "paper" ? "#f5f5f5" : "#0f0f23" }}
        >
          {/* Background Layer (iOS Safari Safe Rendering) */}
          <AnimatePresence mode="wait">
            {bgMode === "gradient" ? (
              <motion.div 
                key="gradient"
                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                className="absolute inset-0 bg-gradient-to-br from-violet-600/40 via-[#0f0f23] to-teal-600/40"
              />
            ) : bgMode === "realistic" ? (
              <motion.img 
                key={`img-${bgSeed}`}
                initial={{ opacity: 0 }} animate={{ opacity: 0.6 }} exit={{ opacity: 0 }} transition={{ duration: 1 }}
                className="absolute inset-0 w-full h-full object-cover"
                crossOrigin="anonymous"
                src={`https://picsum.photos/800/800?random=${bgSeed}&blur=2`}
                alt="realistic background"
              />
            ) : (
              <motion.img 
                key="paper"
                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 0.5 }}
                className="absolute inset-0 w-full h-full object-cover opacity-50 mix-blend-normal"
                crossOrigin="anonymous"
                src={`https://images.unsplash.com/photo-1601662528567-526cd06f6582?q=80&w=1080&auto=format&fit=crop`}
                alt="vintage paper"
              />
            )}
          </AnimatePresence>
          
          {/* Content Layer */}
          <div className="relative z-10 w-full">
            {/* Native img tag instead of next/image for better html-to-image support */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img 
              src="/logo-icon.png" 
              alt="WelGPT" 
              width={32} 
              height={32} 
              className={`mx-auto mb-8 ${bgMode === "paper" ? "opacity-30 invert" : "opacity-80"}`} 
            />
            <h2 className={`text-2xl md:text-3xl font-serif italic leading-relaxed mb-6 ${bgMode === "paper" ? "text-[#2a2a2a] font-medium" : "text-white font-medium drop-shadow-md"}`}>
              &quot;{quote}&quot;
            </h2>
            <p className={`text-sm tracking-widest uppercase ${bgMode === "paper" ? "text-[#555] font-semibold" : "text-gray-300 font-medium drop-shadow-md"}`}>
              — {author}
            </p>
          </div>
          
          {/* Watermark for sharing */}
          <div className={`absolute bottom-6 left-0 right-0 text-center z-10 opacity-50`}>
            <p className={`text-[10px] font-mono tracking-widest ${bgMode === "paper" ? "text-gray-500" : "text-white"}`}>APP.WELGPT.SPACE</p>
          </div>
        </div>
      </motion.div>

      {/* Action Buttons */}
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
        className="flex flex-wrap items-center justify-center gap-4 mt-10"
      >
        <button 
          onClick={fetchNewQuote}
          disabled={isLoading}
          className="flex items-center gap-2 px-6 py-3 rounded-full bg-white/10 hover:bg-white/20 text-white font-medium transition-colors border border-white/5 disabled:opacity-50"
        >
          {isLoading ? <Loader2 size={18} className="animate-spin" /> : <Sparkles size={18} />}
          {isLoading ? "Generating..." : "Generate New"}
        </button>
        <button 
          onClick={handleShare}
          className="flex items-center gap-2 px-6 py-3 rounded-full bg-gradient-to-r from-[#f09433] via-[#dc2743] to-[#bc1888] hover:opacity-90 text-white font-medium transition-opacity shadow-lg shadow-pink-500/20"
        >
          <Share2 size={18} />
          Share to IG
        </button>
      </motion.div>
    </div>
  );
}
